<?php

namespace HTD\classes;

if(!defined('ABSPATH')){
	exit; // Silence is golden
}

class HTD_Init extends HTD_Abstract_Init {

	/**
	 * Adds the frontend hooks
	 * @return void
	 */
	protected function add_actions() {
		parent::add_actions(); // TODO: Change the autogenerated stub

		add_action('wp_enqueue_scripts', array($this,'add_scripts'));
	}

	public function add_scripts(){
		if(!is_admin()){
			$this->enqueue_style('htd-css-front',$this->theme_uri . '/css/style.min.css');
			$this->enqueue_script('htd-script',$this->theme_uri . '/js/dist/index.min.js',array('jquery'),false, true);
		}
	}

}