<?php


namespace HTD\admin\classes;

use HTD\classes\HTD_Abstract_Init;
use HTD\classes\HTD_Const;

if(!defined('ABSPATH')){
	exit; // Silence is golden
}

class HTD_Admin_Init extends HTD_Abstract_Init{

	/**
	 * Adds the admin area hooks
	 * @return void
	 */
	protected function add_actions() {
		parent::add_actions(); // TODO: Change the autogenerated stub
		add_action('admin_menu', array($this,'register_custom_menu'));
		add_action('admin_enqueue_scripts', array($this,'add_scripts'));
	}

	/**
	 * Register custom menu for the admin area
	 *
	 * @return void
	 */
	public function register_custom_menu(){
		add_menu_page(__("Theme settings", HTD_Const::T),__("Theme settings", HTD_Const::T), 'manage_options','htd-theme-settings',array($this,'settings'),'dashicons-dashboard',60);
	}

	/**
	 * Add theme settings template
	 *
	 * @return void
	 */
	public function settings(){
		$this->template('settings.php');
	}

	/**
	 * Add admin scripts
	 *
	 * @param $hook
	 * @return void
	 */

	public function add_scripts($hook){
		if ($hook !== "toplevel_page_htd-theme-settings"){
			return;
		}

		wp_enqueue_media();
		$this->enqueue_style('htd-css-admin', $this->theme_uri . '/' . $this->include_dir . '/css/style.min.css');
		$this->enqueue_script('htd-admin-script', $this->theme_uri . '/' . $this->include_dir . '/js/dist/index.min.js', array('jquery'),false,true);

		wp_localize_script('htd-admin-script','HTDData', $this->get_localization());
	}
	public function get_localization() {
		return array(
			't' => include($this->theme_path . '/i18n.php')
		);
	}
}