<?php


namespace HTD\admin\classes;

use HTD\classes\HTD_Abstract_Init;

if(!defined('ABSPATH')){
	exit; // Silence is golden
}

class HTD_Admin_Init extends HTD_Abstract_Init{

	/**
	 * Adds the admin area hooks
	 * @return void
	 */
	protected function add_actions() {
		parent::add_actions(); // TODO: Change the autogenerated stub
	}
}